server:
  port: 8082
spring:
  application:
    name:menu-service
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5432/menu
    username: 'softakcess'
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
